version: '3.8'

services:
  digital-employee:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 未来可以添加的服务
  # redis:
  #   image: redis:6-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: digital_employee
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   redis_data:
#   postgres_data: